
package main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;

public class frmInsurance extends javax.swing.JFrame {
DbConnection DbConn = new DbConnection();
    public frmInsurance() {
        initComponents();
        DbConn.DoConnect();
        FillCombo();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(frmInsurance.DISPOSE_ON_CLOSE);
        cmbName.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {txtName.setText(cmbName.getSelectedItem().toString());
            FillScheme();}
        });
    }
    private void FillScheme(){
        cmbScheme.removeAllItems();
        try{
            DbConn.SQLQuery = "Select im_name,im_scheme from tblinsurancemaster where im_name = ?";
            DbConn.pstmt = DbConn.conn.prepareStatement(DbConn.SQLQuery);
            DbConn.pstmt.setString(1, cmbName.getSelectedItem().toString());
            DbConn.rs = DbConn.pstmt.executeQuery();
            while (DbConn.rs.next()){
                cmbScheme.addItem(DbConn.rs.getString("im_scheme"));
            }
            cmbScheme.setSelectedIndex(-1);
            DbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void FillCombo(){
        cmbName.removeAllItems();
        try{
            DbConn.SQLQuery = "Select distinct im_name from tblinsurancemaster order by im_name";
            DbConn.pstmt = DbConn.conn.prepareStatement(DbConn.SQLQuery);
            DbConn.rs = DbConn.pstmt.executeQuery();
            while (DbConn.rs.next()){
                cmbName.addItem(DbConn.rs.getString("im_name"));
            }
            cmbName.setSelectedIndex(-1);
            DbConn.pstmt.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtScheme = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbName = new javax.swing.JComboBox<>();
        cmbScheme = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel2.setText("Scheme:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 290, -1));
        jPanel1.add(txtScheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 290, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbNameMouseReleased(evt);
            }
        });
        cmbName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbNameKeyReleased(evt);
            }
        });
        jPanel2.add(cmbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 280, -1));

        cmbScheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbScheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbSchemeMouseReleased(evt);
            }
        });
        cmbScheme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbSchemeKeyReleased(evt);
            }
        });
        jPanel2.add(cmbScheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 280, -1));

        jLabel3.setText("Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setText("Scheme:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (cmbName.getSelectedIndex() == -1){
        try{
            DbConn.pstmt = DbConn.conn.prepareStatement("insert into tblinsurancemaster (im_name,im_scheme) values (?,?)");
            DbConn.pstmt.setString(1, txtName.getText());
            DbConn.pstmt.setString(2, txtScheme.getText());
            DbConn.pstmt.execute();
            JOptionPane.showMessageDialog(this, "New Insurance Saved");
            DbConn.pstmt.close();
            this.dispose();
            revalidate();
            repaint();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }else{
        try{
            DbConn.pstmt = DbConn.conn.prepareStatement("insert into tblinsurancemaster (im_name,im_scheme) values (?,?)");
            DbConn.pstmt.setString(1, txtName.getText());
            DbConn.pstmt.setString(2, txtScheme.getText());
            DbConn.pstmt.execute();
            JOptionPane.showMessageDialog(this, "New Scheme Saved");
            DbConn.pstmt.close();
            revalidate();
            repaint();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cmbNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbNameKeyReleased
        txtName.setText(cmbName.getSelectedItem().toString());
    }//GEN-LAST:event_cmbNameKeyReleased

    private void cmbNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbNameMouseReleased
        
    }//GEN-LAST:event_cmbNameMouseReleased

    private void cmbSchemeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSchemeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSchemeMouseReleased

    private void cmbSchemeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSchemeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSchemeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInsurance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInsurance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JComboBox<String> cmbScheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScheme;
    // End of variables declaration//GEN-END:variables
}